### ISSUE TITLE
login does not work

### ISSUE THREAD

**Issue by BennerLukas** [BennerLukas/biblio#37]
Traceback (most recent call last)
File "C:\ProgramData\Anaconda3\Lib\site-packages\flask\app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "C:\ProgramData\Anaconda3\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "C:\ProgramData\Anaconda3\Lib\site-packages\flask\app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\ProgramData\Anaconda3\Lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\ProgramData\Anaconda3\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "C:\ProgramData\Anaconda3\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\ProgramData\Anaconda3\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\ProgramData\Anaconda3\Lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\ProgramData\Anaconda3\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "C:\ProgramData\Anaconda3\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Users\alina\Dropbox\Mein PC (LAPTOP-J5RO143S)\Desktop\Duales Studium\Uni Mannheim\Theoriephase\3.Semester\Datenbanken I\Projekt\biblio\src\frontend\app\views.py", line 208, in logged_in
session['user_id'] = bib.set_user(request.form['user_name'], request.form['password'])
File "C:\Users\alina\Dropbox\Mein PC (LAPTOP-J5RO143S)\Desktop\Duales Studium\Uni Mannheim\Theoriephase\3.Semester\Datenbanken I\Projekt\biblio\src\frontend\api\biblio.py", line 129, in set_user
n_id = int(df['n_user_id'])
TypeError: 'bool' object is not subscriptable
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by BennerLukas** [comment]
db not init
